packages:
  - ./packages/*
  - ./apps/*

catalogs:
  ai:
    '@anthropic-ai/sdk': ^0.71.0
    '@mcp-ui/server': ^6.0.0
    '@modelcontextprotocol/inspector': ^0.19.0
    '@opencode-ai/plugin': ^1.1.44
  lint:
    '@eslint/compat': ^2.0.0
    '@eslint/js': ^9.36.0
    '@types/eslint-scope': ^8.3.2
    '@typescript-eslint/parser': ^8.44.0
    '@typescript-eslint/types': ^8.44.0
    eslint: ^9.36.0
    eslint-config-prettier: ^10.0.1
    eslint-plugin-import: ^2.32.0
    eslint-plugin-pnpm: ^1.3.0
    eslint-plugin-svelte: ^3.12.5
    globals: ^17.0.0
    prettier: ^3.4.2
    prettier-plugin-svelte: ^3.3.3
    svelte-eslint-parser: ^1.4.0
    typescript-eslint: ^8.44.0
  orm:
    '@libsql/client': ^0.17.0
    drizzle-kit: ^0.31.0
    drizzle-orm: ^0.45.0
  svelte:
    '@sveltejs/adapter-vercel': ^6.0.0
    '@sveltejs/kit': ^2.42.2
    '@sveltejs/vite-plugin-svelte': ^6.0.0
    svelte: ^5.47.0
    svelte-check: ^4.0.0
  tmcp:
    '@tmcp/adapter-valibot': ^0.1.4
    '@tmcp/transport-http': ^0.8.4
    '@tmcp/transport-in-memory': ^0.0.5
    '@tmcp/transport-stdio': ^0.4.0
    tmcp: ^1.19.0
  tooling:
    '@changesets/cli': ^2.29.7
    '@svitejs/changesets-changelog-github-compact': ^1.2.0
    '@types/estree': ^1.0.8
    '@types/node': ^24.3.1
    '@valibot/to-json-schema': ^1.5.0
    '@vercel/analytics': ^1.5.0
    dotenv: ^17.2.3
    node-resolve-ts: ^1.0.2
    publint: ^0.3.13
    sade: 1.8.1
    ts-blank-space: ^0.7.0
    tsdown: ^0.20.0
    typescript: ^5.0.0
    valibot: ^1.2.0
    vite: ^7.0.4
    vite-plugin-devtools-json: ^1.0.0
    vitest: ^4.0.0
    zimmerframe: ^1.1.4

useNodeVersion: 22.19.0
